eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

microservice.user-service.endpoint=http://user-service
microservice.contact-service.endpoint=http://contact-service/contact/user/
